- import_playbook: get-VM-IP.yaml

- name: Install .NET
  hosts: azure
  become: true
  tasks:
    - name: Add epel-release repo
      yum:
        name: epel-release
        state: present
    - name: Install nginx
      yum:
        name: nginx
        state: present
    - name: Install MS repo
      yum:
        name: 'https://packages.microsoft.com/config/centos/7/packages-microsoft-prod.rpm'
        state: present
    - name: Install .NET SDK
      yum:
        name: dotnet-sdk-5.0
        state: present
    - name: Copy app
      synchronize:
        src: .net-app/
        dest: /app
        use_ssh_args: yes
    - name: Publish app
      command: dotnet publish --configuration Release
      args:
        chdir: /app
    - name: Copy nginx config
      template:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf
    - name: Set httpd_can_network_connect flag on and keep it persistent across reboots
      command: setsebool -P httpd_can_network_connect 1
    - name: Restart NGiNX
      service:
        name: nginx
        state: restarted
    - name: Copy systemd service
      template:
        src: kestrel-helloapp.service
        dest: /etc/systemd/system/kestrel-helloapp.service 
    - name: Just force systemd to reread configs (2.4 and above)
      ansible.builtin.systemd:
        daemon_reload: yes
    - name: Enable service kestrel-helloapp and ensure it is not masked
      ansible.builtin.systemd:
        name: kestrel-helloapp.service
        enabled: yes
        masked: no
        state: started
    - name: Create Network Security Group that allows HTTP
      become: false
      delegate_to: localhost
      azure_rm_securitygroup:
        resource_group: "{{ resource_group }}"
        name: myNetworkSecurityGroup
        rules:
          - name: HTTP
            protocol: Tcp
            destination_port_range: 80
            access: Allow
            priority: 1002
            direction: Inbound
    - name: print URL
      debug: msg="The site is available on http://{{ansible_host}}"