- name: Get VM IP
  hosts: localhost
  vars:
    resource_group: "ansibleVM"
    vm:
      username: azureuser
      public_ip_name: "myPublicIP"
  tasks:
    - name: Get network interface details
      azure_rm_publicipaddress_info:
        resource_group: "{{resource_group}}"
        name: "{{vm.public_ip_name}}"
      register: azure_ips
    - name: print public IP
      debug: msg="Public ip is {{azure_ips.publicipaddresses[0].ip_address}}"
    - name: Add host to group azure
      add_host:
        name: '{{ azure_ips.publicipaddresses[0].ip_address }}'
        groups: azure
        ansible_user: '{{vm.username}}'
        ansible_ssh_private_key_file: "azure_rsa"
        ansible_ssh_extra_args: "-o IdentitiesOnly=yes -o StrictHostKeyChecking=no"
        ansible_host_key_checking: false
        resource_group: "{{resource_group}}"